<p>Thank you for visiting nature.com.<br>You are using a browser version with limited support for CSS.<br>To obtain
            the best experience, we recommend you use a more up to date browser (or turn off compatibility mode in
            Internet Explorer).<br>In the meantime, to ensure continued support, we are displaying the site without styles
            and JavaScript.AdvertisementYou can also search for this author in You have full access to this article via your institution.A few weeks after receiving an experimental cancer therapy that turns immune cells into tumour-killing hunters, Doug Olson’s doctor sat him down to give him news of his progress.<br>“He said, ‘Doug, we cannot find a single cancer cell in your body,’” Olson recalls.<br>“I was pretty convinced that I was done with cancer.”Olson’s doctors, however, weren’t so sure.<br>The year was 2010, and Olson was one of the first people with chronic lymphocytic leukaemia to receive the treatment, called CAR-T cell therapy.<br>When his doctors — including Carl June and David Porter at the University of Pennsylvania in Philadelphia — wrote the protocol for the clinical trial that Olson was involved in, they hoped that the genetically engineered cells might survive for a month in his body.<br>They knew that cancer research could be heartbreaking; they didn’t dare to expect a cure.But more than ten years later, the immune cells continue to patrol Olson’s blood and he remains in remission.<br>June is finally ready to admit what Olson suspected all along.<br>“We can now conclude that CAR T cells can actually cure patients with leukaemia,” June told reporters at a press briefing describing results that were published in  on 2 February.CAR-T cell therapies involve removing immune cells called T cells from a person with cancer, and genetically altering them so that they produce proteins — called chimeric antigen receptors, or CARs — that recognize cancer cells.<br>The cells are then reinfused into the person, in the hope that they will seek out and destroy tumours.In the years since Olson’s treatment, five CAR-T cell therapies have been approved by the US Food and Drug Administration, to treat leukaemias, lymphomas and myelomas.<br>June estimates that tens of thousands of people have received CAR-T cell treatment.
 Building better CAR-T therapiesBut the therapy is expensive, risky and technically demanding.<br>It remains a last resort, to be used when all other treatments have failed.<br>Despite the treatment’s success for Olson, not everyone experiences durable remission of their cancer.<br>In the beginning, only about 25-35% of CAR-T cell recipients with chronic lymphocytic leukaemia experienced a complete remission of their cancer, says Porter.<br>With refinement, that percentage has increased over the years, he says, but some of these initial successes still lead to relapse.<br>Tracking the treatment long-term could reveal clues as to what factors are important for lasting CAR-T cell success.For more than ten years, Porter and his colleagues analysed the CAR-T cells in Olson and one other person treated in 2010, tracing the cells’ evolution and looking for any signs of safety concerns.They found that the CAR T cells persisted, but the characteristics of the population shifted over time.<br>Soon after infusion, a prominent population of T cells called CD8 cells emerged.<br>These are sometimes called killer T cells, and can identify and destroy cells that display unusual proteins, such as  or .But over the years, a different type of CAR T cell became dominant.<br>CD4 T cells can take on a variety of functions in the immune system, but the researchers showed that both study participants had CD4 cells with characteristics suggesting that they would be capable of killing leukaemia cells.Olson and the other participant now have no signs of leukaemia.<br>It’s unclear whether the CAR T cells killed all the leukaemia cells soon after they were introduced, or if the cells that continue to patrol are able to destroy any leukaemia cells before they reach detectable levels.
 Highly mutated cancers respond better to immune therapy“The potential impact of CAR T is tremendous,” says Nirali Shah, a paediatric haematologist at the US National Cancer Institute in Bethesda, Maryland.<br>This study “gives you a proof of concept about the safety of having long-term persistence and integration of the T cells into your body”.It remains to be seen, she adds, how well the findings from these two individuals with chronic lymphocytic leukaemia will translate to other diseases.<br>Efforts are underway to use CAR-T cell approaches to treat solid tumours, such as prostate tumours and the devastating brain cancer glioblastoma.<br>In January, researchers reported success in using the cells to destroy scar tissue in the heart — an approach that could one day be used to treat cardiac fibrosis.In the years after his treatment, Olson returned to his career in medical diagnostics.<br>He committed to staying healthy, and his son talked him into running half marathons.<br>“If my cancer was gone, I certainly didn’t want to die of a heart attack,” he says.<br>Eventually, he decided to go public with the story of his recovery, and serve as a mentor for other people with cancer.He tries to give them hope, he says: “If there isn’t a cure for their cancer today, there’s a reasonable chance that around the corner, there’s going to be one.”Melenhorst, J.<br>J.<br>  https://doi.org/10.1038/s41586-021-04390-6 (2022). 
     
                Rurik, J.<br>G.<br>  , 91–96 (2022). 
     
     
                         Helsinki or Turku, FinlandOeiras, PortugalCharlestown, MA, United StatesLondon, United KingdomYou have full access to this article via your institution.An essential round-up of science news, opinion and analysis, delivered to your inbox every weekday.Sign up for the  newsletter — what matters in science, free to your inbox daily.
                
            
                
                
    
    
    


                
    
    
    

            © 2022 Springer Nature LimitedThank you for visiting nature.com.<br>You are using a browser version with limited support for CSS.<br>To obtain
            the best experience, we recommend you use a more up to date browser (or turn off compatibility mode in
            Internet Explorer).<br>In the meantime, to ensure continued support, we are displaying the site without styles
            and JavaScript.AdvertisementYou can also search for this author in You have full access to this article via your institution.A few weeks after receiving an experimental cancer therapy that turns immune cells into tumour-killing hunters, Doug Olson’s doctor sat him down to give him news of his progress.<br>“He said, ‘Doug, we cannot find a single cancer cell in your body,’” Olson recalls.<br>“I was pretty convinced that I was done with cancer.”Olson’s doctors, however, weren’t so sure.<br>The year was 2010, and Olson was one of the first people with chronic lymphocytic leukaemia to receive the treatment, called CAR-T cell therapy.<br>When his doctors — including Carl June and David Porter at the University of Pennsylvania in Philadelphia — wrote the protocol for the clinical trial that Olson was involved in, they hoped that the genetically engineered cells might survive for a month in his body.<br>They knew that cancer research could be heartbreaking; they didn’t dare to expect a cure.But more than ten years later, the immune cells continue to patrol Olson’s blood and he remains in remission.<br>June is finally ready to admit what Olson suspected all along.<br>“We can now conclude that CAR T cells can actually cure patients with leukaemia,” June told reporters at a press briefing describing results that were published in  on 2 February.CAR-T cell therapies involve removing immune cells called T cells from a person with cancer, and genetically altering them so that they produce proteins — called chimeric antigen receptors, or CARs — that recognize cancer cells.<br>The cells are then reinfused into the person, in the hope that they will seek out and destroy tumours.In the years since Olson’s treatment, five CAR-T cell therapies have been approved by the US Food and Drug Administration, to treat leukaemias, lymphomas and myelomas.<br>June estimates that tens of thousands of people have received CAR-T cell treatment.
 Building better CAR-T therapiesBut the therapy is expensive, risky and technically demanding.<br>It remains a last resort, to be used when all other treatments have failed.<br>Despite the treatment’s success for Olson, not everyone experiences durable remission of their cancer.<br>In the beginning, only about 25-35% of CAR-T cell recipients with chronic lymphocytic leukaemia experienced a complete remission of their cancer, says Porter.<br>With refinement, that percentage has increased over the years, he says, but some of these initial successes still lead to relapse.<br>Tracking the treatment long-term could reveal clues as to what factors are important for lasting CAR-T cell success.For more than ten years, Porter and his colleagues analysed the CAR-T cells in Olson and one other person treated in 2010, tracing the cells’ evolution and looking for any signs of safety concerns.They found that the CAR T cells persisted, but the characteristics of the population shifted over time.<br>Soon after infusion, a prominent population of T cells called CD8 cells emerged.<br>These are sometimes called killer T cells, and can identify and destroy cells that display unusual proteins, such as  or .But over the years, a different type of CAR T cell became dominant.<br>CD4 T cells can take on a variety of functions in the immune system, but the researchers showed that both study participants had CD4 cells with characteristics suggesting that they would be capable of killing leukaemia cells.Olson and the other participant now have no signs of leukaemia.<br>It’s unclear whether the CAR T cells killed all the leukaemia cells soon after they were introduced, or if the cells that continue to patrol are able to destroy any leukaemia cells before they reach detectable levels.
 Highly mutated cancers respond better to immune therapy“The potential impact of CAR T is tremendous,” says Nirali Shah, a paediatric haematologist at the US National Cancer Institute in Bethesda, Maryland.<br>This study “gives you a proof of concept about the safety of having long-term persistence and integration of the T cells into your body”.It remains to be seen, she adds, how well the findings from these two individuals with chronic lymphocytic leukaemia will translate to other diseases.<br>Efforts are underway to use CAR-T cell approaches to treat solid tumours, such as prostate tumours and the devastating brain cancer glioblastoma.<br>In January, researchers reported success in using the cells to destroy scar tissue in the heart — an approach that could one day be used to treat cardiac fibrosis.In the years after his treatment, Olson returned to his career in medical diagnostics.<br>He committed to staying healthy, and his son talked him into running half marathons.<br>“If my cancer was gone, I certainly didn’t want to die of a heart attack,” he says.<br>Eventually, he decided to go public with the story of his recovery, and serve as a mentor for other people with cancer.He tries to give them hope, he says: “If there isn’t a cure for their cancer today, there’s a reasonable chance that around the corner, there’s going to be one.”Melenhorst, J.<br>J.<br>  https://doi.org/10.1038/s41586-021-04390-6 (2022). 
     
                Rurik, J.<br>G.<br>  , 91–96 (2022). 
     
     
                         Helsinki or Turku, FinlandOeiras, PortugalCharlestown, MA, United StatesLondon, United KingdomYou have full access to this article via your institution.An essential round-up of science news, opinion and analysis, delivered to your inbox every weekday.Sign up for the  newsletter — what matters in science, free to your inbox daily.
                
            
                
                
    
    
    


                
    
    
    

            © 2022 Springer Nature LimitedThank you for visiting nature.com.<br>You are using a browser version with limited support for CSS.<br>To obtain
            the best experience, we recommend you use a more up to date browser (or turn off compatibility mode in
            Internet Explorer).<br>In the meantime, to ensure continued support, we are displaying the site without styles
            and JavaScript.AdvertisementYou can also search for this author in You have full access to this article via your institution.A few weeks after receiving an experimental cancer therapy that turns immune cells into tumour-killing hunters, Doug Olson’s doctor sat him down to give him news of his progress.<br>“He said, ‘Doug, we cannot find a single cancer cell in your body,’” Olson recalls.<br>“I was pretty convinced that I was done with cancer.”Olson’s doctors, however, weren’t so sure.<br>The year was 2010, and Olson was one of the first people with chronic lymphocytic leukaemia to receive the treatment, called CAR-T cell therapy.<br>When his doctors — including Carl June and David Porter at the University of Pennsylvania in Philadelphia — wrote the protocol for the clinical trial that Olson was involved in, they hoped that the genetically engineered cells might survive for a month in his body.<br>They knew that cancer research could be heartbreaking; they didn’t dare to expect a cure.But more than ten years later, the immune cells continue to patrol Olson’s blood and he remains in remission.<br>June is finally ready to admit what Olson suspected all along.<br>“We can now conclude that CAR T cells can actually cure patients with leukaemia,” June told reporters at a press briefing describing results that were published in  on 2 February.CAR-T cell therapies involve removing immune cells called T cells from a person with cancer, and genetically altering them so that they produce proteins — called chimeric antigen receptors, or CARs — that recognize cancer cells.<br>The cells are then reinfused into the person, in the hope that they will seek out and destroy tumours.In the years since Olson’s treatment, five CAR-T cell therapies have been approved by the US Food and Drug Administration, to treat leukaemias, lymphomas and myelomas.<br>June estimates that tens of thousands of people have received CAR-T cell treatment.
 Building better CAR-T therapiesBut the therapy is expensive, risky and technically demanding.<br>It remains a last resort, to be used when all other treatments have failed.<br>Despite the treatment’s success for Olson, not everyone experiences durable remission of their cancer.<br>In the beginning, only about 25-35% of CAR-T cell recipients with chronic lymphocytic leukaemia experienced a complete remission of their cancer, says Porter.<br>With refinement, that percentage has increased over the years, he says, but some of these initial successes still lead to relapse.<br>Tracking the treatment long-term could reveal clues as to what factors are important for lasting CAR-T cell success.For more than ten years, Porter and his colleagues analysed the CAR-T cells in Olson and one other person treated in 2010, tracing the cells’ evolution and looking for any signs of safety concerns.They found that the CAR T cells persisted, but the characteristics of the population shifted over time.<br>Soon after infusion, a prominent population of T cells called CD8 cells emerged.<br>These are sometimes called killer T cells, and can identify and destroy cells that display unusual proteins, such as  or .But over the years, a different type of CAR T cell became dominant.<br>CD4 T cells can take on a variety of functions in the immune system, but the researchers showed that both study participants had CD4 cells with characteristics suggesting that they would be capable of killing leukaemia cells.Olson and the other participant now have no signs of leukaemia.<br>It’s unclear whether the CAR T cells killed all the leukaemia cells soon after they were introduced, or if the cells that continue to patrol are able to destroy any leukaemia cells before they reach detectable levels.
 Highly mutated cancers respond better to immune therapy“The potential impact of CAR T is tremendous,” says Nirali Shah, a paediatric haematologist at the US National Cancer Institute in Bethesda, Maryland.<br>This study “gives you a proof of concept about the safety of having long-term persistence and integration of the T cells into your body”.It remains to be seen, she adds, how well the findings from these two individuals with chronic lymphocytic leukaemia will translate to other diseases.<br>Efforts are underway to use CAR-T cell approaches to treat solid tumours, such as prostate tumours and the devastating brain cancer glioblastoma.<br>In January, researchers reported success in using the cells to destroy scar tissue in the heart — an approach that could one day be used to treat cardiac fibrosis.In the years after his treatment, Olson returned to his career in medical diagnostics.<br>He committed to staying healthy, and his son talked him into running half marathons.<br>“If my cancer was gone, I certainly didn’t want to die of a heart attack,” he says.<br>Eventually, he decided to go public with the story of his recovery, and serve as a mentor for other people with cancer.He tries to give them hope, he says: “If there isn’t a cure for their cancer today, there’s a reasonable chance that around the corner, there’s going to be one.”Melenhorst, J.<br>J.<br>  https://doi.org/10.1038/s41586-021-04390-6 (2022). 
     
                Rurik, J.<br>G.<br>  , 91–96 (2022). 
     
     
                         Helsinki or Turku, FinlandOeiras, PortugalCharlestown, MA, United StatesLondon, United KingdomYou have full access to this article via your institution.An essential round-up of science news, opinion and analysis, delivered to your inbox every weekday.Sign up for the  newsletter — what matters in science, free to your inbox daily.
                
            
                
                
    
    
    


                
    
    
    

            © 2022 Springer Nature Limited</p>
