<p>I know the pandemic has been hard; but, we've got to fight to keep our peace through this and not attack others during this time, where we can.I'm not going to look through rose-tinted glasses and suggest "things were better in the good ol' days".<br>Contrarian reactions to top posts are the bread-and-butter of a healthy message board.However, to me it feels like the  of these contrarian takes have gone down.<br>People seem far more 'committed' to pushing their positions to incense others with overgeneralizing karma-clickbait.<br>This causes the dialectic to become more of a debate instead of a deliberation, and to me the latter is far more useful and engaging.With that said, I also know that my tastes change as I get older, so this could truly be my own delusion.
      
      I too am getting older, and while I don’t feel I’m becoming galvanized per se, I think my tolerance for those not acting in good faith has rapidly approached zero.<br>If the data speaks and the counterparty opposes facts, there is no way to have a productive discussion.<br>An example from my own experience would be when talking to someone about climate change, which they don’t believe in because “God will make sure it all works out”.<br>There is no value in engaging in those situations, and similar anecdotes can be found here.<br>Belief systems and mental models can be rigid.
      
      
      Internet arguing follows the same logic.<br>If I logically out-fence you by being an asshole, what have I gained? What have we gained?Whereas if I politely and respectfully describe why eating Irish babies is a solution to overpopulation of the lower classes [0], we all feel better about ourselves, even if you decline to agree with me.[0] 
      
      The thing is, from a neutral external perspective, when one side claims "there is no climate change, only God's will" and the other side claims "Climate change is man-made and will escalate to the point of irreversibility if nothing is done", then .<br>And yet, "listen to both sides!!!"-style arguments result in complete bullshit given the attention of millions of people.Democratic discourse fundamentally needs  to debate, not lies, propaganda or un-verifiable anecdotes.<br>People who come to a democratic discourse without facts deserve no time of democratic people.<br>Democracy itself is  with disinformation from all kind of sources, both foreign (Russian and Chinese propaganda) and domestic (corporate or otherwise financially motivated shills, authoritarian politicians willing to grab power).
      It’s astounding really, and these data points have helped me recalibrate my expectations of fellow humans, as well as my empathy for them.
      Gonna need a link to one of those threads full of citations on this claim, because this is not at all my understanding.<br>Even if we had a magic wand that would reduce anthropogenic CO2 (and other greenhouse gas) emissions to zero overnight, we're  already far above historic atmospheric CO2 concentrations and will be paying the price.
      
      That may be the difference.<br> A few years ago, more of the contrarian takes were in good faith, with real thought behind them.<br> You could learn something new from them, even if you didn't completely agree with them.<br> That also meant that, when you were confronted with a contrarian take, you were more likely to expect that it was made in good faith.<br> This led to a different feel for the whole site.Now it seems that more of the contrarian (and even mainstream) takes are just repeating talking points.<br> They are, in CapitalistCartr's words, "a set of recordings", so they're no point trying to have a discussion.I don't know how to get back to where HN was five years ago.<br> I can feel the difference, and I prefer the old version.#OldManYellsAtClouds, I guess...
      
      Part of the reason is: while I am thoughtful, reasonably well-informed individual, I never felt up to the task of putting in enough effort to create an HN-worthy comment.<br>This was inspired almost entirely by the _quality_ of the kinds of comments that I saw over the years -- at least for the kinds of posts that drew my attention.- Many (most?) of the comments were made by experts
- They often included disclaimers, especially when the poster considered themselves an amateur
- They often included sources and links
- They were conspicuously respectful and humane
- Meta-comments were productive, and typically stopped propagation of nastiness before it could take rootOften enough, comments would truly enrich the original post, and I was truly grateful for them.This was a stark contrast with the subreddits that I frequented.<br>(I gave up on reddit a few years when they changed the default format to be more attention-greedy.)From what I've seen, HN has become increasingly noisy -- at times, it's angry -- but overall, it just feels loud and crowded.For that reason, I've basically stopped reading comments at all, even if there is high-quality content in there.<br>It is a damn shame.
      I think this is part of the real reason.<br>More people have been coming there since I joined (2015 I think?).<br>The submissions were also more technical then, a bit more, not much more.
      
      Examples?  Sometimes interest in particular types of "new" ideas is just naivete, and seeing those "new" ideas fail or not live up to the hype can lead to a new appreciation of certain aspects of the status quo.
      This is just one example of how this type reacts to particular issues, the full impact is pervasive throughout the whole site.Yes, I know there is an irony in me generalizing about this type of person, but I'm unsure how else to talk about it.
      
      Getting hired by a FAANG is the antithesis of doing a startup, or doing some original research, or even working on a clever hack just for the joy of it.
      Maybe a bit of it is just me getting older, but I think most of it is observing that a lot of things are actively getting worse, and thus prioritizing "stopping the bleeding".<br>A concrete example of this would be Biden as a politician, 5 years ago I would have hated him as useless (not improving things) and mildly corrupt, now I don't mind him as useless (not making things worse) and only mildly corrupt - with the unfortunate reality that that is the best option the US had.PS.<br>Let's try and keep this thread from becoming a debate about Biden and politicians, he's a useful example but not the point, I don't expect everyone to agree with my assessment.
      
      
      That said, I think the tone on HN is fairly good, people are not sugarcoating things, they're not veiling their views with courtesy, and they're generally presenting arguments for consideration, and if insults are made, they're usually insults of ideas, not people.So maybe I'm just in the "negative asshole camp" but I think it's very refreshing to have conversations on HN, because my views are often challenged, and I am forced to reconsider and adjust, while at the same time, I feel that my own points are being considered, rather than automatically discarded as is often the case in mainstream social media, where discussions are not had to find understanding or truth, but to "win".
      I agree.I've been visiting HN for years, but I'm pretty new as a commenter.<br>AFAICS the tone is rather nicely controlled by the mods (hi, dang!) and the community.<br>I'm glad it's a place where people can say what they think, in fairly direct terms; I'm also glad that people are expected to think before they say.Whether conversations here are more polarized than in the past, I can't say.<br>But societies have become more polarized lately; people are angrier, there's a lot more othering going on.It helps  that HN generally disapproves of political debates.
      Generally, HN trends towards the former, and that's one of the things I love about it! You can make a good point  I can disagree with you!One of the most counter-intuitive tenets of forum community management is the only winning move is not to engage with bad behavior.A downvote +  replying to a poorly behaving commenter is orders of magnitude more powerful and instructive than any reply.(And also, the distinction between "downvote because I disagree" & "downvote because you're breaking forum norms." We're at our best when we promote healthy debate, and disincentivize bad behavior, instead of "bad thoughts.")
      It's interesting that this post hits the front page on the same day that Facebook announces (admits to?) its first user drop.<br>Everyone is just getting sick of being social online.<br>From here on out, content is king.In 10 years we'll look at the Facebook news feed as being the necessary intermediate step between Web 2.0 and whatever TikTok becomes.
      I think as remote work has become more common, many engineers are reaching to social media sites like HN to fill the void left by previous in-person office banter.<br>The good comments are still there, but it feels like more work than ever to find them among the noise.<br>I've also noticed an increase in the number of familiar HN screen names that pop up with the same angry perspectives on every thread of certain hot topics (Facebook, economics, cloud hosting).This effect isn't exclusive to HN.<br>The signal-to-noise ratio of the public forums and Slacks/Discords I frequent has also taken a dive since the start of COVID.
      
      
      1.<br>There seem to be more political topics appearing, for example around handling of COVID or effects of social networks on society.<br>The best comments on these topics ferret out a priori assumptions or find real data to illuminate tradeoffs.<br>But they tend to be drowned out by more shallow comments.<br>I think that's in part because these issues are hard to discuss in a dispassionate way and most of us are simply not very good at it.<br>I'm firmly in this camp, unfortunately.2.<br>HN commentary seems more predictable than it did a few years ago.<br>For example, you post something about how a big company has changed licensing of software you'll likely get a fairly predictable (and long) discussion about the evils of capitalism.<br>I don't think this is a real change.<br>Some HN readers have a more binary view of the world than others and it has always been this way.<br>I think I just notice it more.I still think HN has some of the best commentary available on the web.<br>For all the silly arguments we have (and that I have contributed to eagerly), you still get those gems where somebody who truly understands an issue deeply weighs in and tells it like it is.<br>They have helped me understand countless articles that I would never have understood on my own.<br>I love those comments and hope they never go away.
      In general anonymous commenting was cool for a while but seems to be leading to negative results most places.<br>I’m ready to engage with forums limited to verified real people ex specific situations where personal safety might be at risk (and I’m not in any of those myself now or in the past).
      
      
      What a difficult spot to be in to preserve an internal sense of normal when everything outside it is changing so quickly.<br>I am not neutral at all, and am radical probably in every direction, and nor am I somehow above any of it, but even with the all underlying tension from world events I won't address directly, I don't think any of us will regret any effort we make individually to preserve the relative calm in places like this for its own sake.
      My theory is that, as a site grows, the quality of comments goes down.<br>Perhaps it's because the site is harder to moderate when more people are on it? Perhaps it's because the attention drives in the loonies?Personally, I really like how Hacker News is moderated.<br>(Thanks Dang!)
      
      
      
      
      The pandemic is 2 years old, so not as 'lately' as your describe.<br>Not to mention, it sure looks like it's finally over with loads of countries eliminating restrictions.<br>So anyone angry over pandemic would be happy now.It's not so much that people are more angry, but rather the remaining comments are angry.<br>There's a pretty significant amount of downvote brigading to hide comments and deny viewpoints on HN.Realistically speaking it's identical to what happened to reddit.<br>White supremacists, racists, nazis, EVERYWHERE!
      Post-2020 it looks as if I never will again because my job has gone and been replaced with something else.It doesn't surprise me that Hacker News is different - _being a hacker is different_.It's now been seperated apart from other jobs in society even more - you can look at charts and see that software has basically gone all in on WFH where other office-based jobs have been much more measured.
      The comments have nothing novel to discuss, just endless rehashing of the same battles over and over.<br>Guidelines warn against using the site to wage ideological battles, so I usually just flag and move on.
      
      
      Try to go to  and find interesting small post.<br>I like when they have like 10 comments, but sometimes they have no comments and you can have a nice conversation with the author or someone of the community of HN that is an expert in the subject.<br>[Note: Most of the post in "newest" are not interesting.<br>You must check it for a while until you find one.]
      
      
      I quit slashdot when basically every story started hitting 100+ comments.<br>When 100+ comment stories were maybe once-a-day thing, slashdot was an outstanding board.I have noticed the rule applies very widely, including on subreddits.
      1.<br>People, consciously or not, start forming their comments with upvotes in mind.2.<br>People realize that positive comments don't generate as much discussion as neutral or negative comments.<br>Less discussion, less upvotes.
      
      So  are possibly more angry when interacting with HN lately, or are interpreting more things that aren't angry as angry.Take a few weeks away from HN entirely.<br> It can become addicting, it's often good to seek time apart from any source of anger in your life.
      This is all my opinion but apart from dang doing some type of pull to see if more comments have been reported I don't know how you can get anything other than anecdotal responses here.When I run into a curmudgeon and don't want to deal with them, I just move on.
      Things used to be hopeful and encouraging around here.<br> It's not that way anymore.
      Obligatory reference to the infamous Dropbox comment: The day HN stops helping me see the opposing viewpoint will be a sad day indeed.<br>With that said, there is clear distinction between opposition and opprobrium, and yes, sometimes there's the latter here...<br>but I don't feel it as much.
      I'd also submit that it's far more normal now than say 5 years ago for just the bare disagreement of what I said above to be perceived, by some, as me attacking you, the author of the OP.<br>Which would be an erroneous conclusion as far as I'm concerned.
      but we can't talk about climate shit because people either 1) don't wanna be depressed, 2) aren't willing to accept the rules of the New Climate Regime, 3) are concern trolls, 4) stuck in old, outdated political lines.so it's just a slow motion death march into the future.<br>fuck.
      (Not to deny that systemic racism is real:  one book about the Watts riot pointed out that many black people lived in communities where they didn't see a lot of white people and thus got distorted ideas of 'white privilege' because they never saw white people on TV who had real life troubles.)Before Trump I think the SJW contingent was worse but now the right-wing special snowflakes who think they have something so precious to say about why BLM sucks are insufferable that they've got the right to shove it down our throats.These sides both agree that:  (1) they are victims,  and (2) specifically victims of a conspiracy that controls Hacker News.<br> They're terribly offended that their posts get flagged and even offended that their comments get downvoted.<br> If there wasn't downvoting to complain about they'd probably complain that their comments aren't getting upvoted.Personally I flag anything about "X is being censored by Y" unless Y is the People's Republic of China.<br> In a world where we're overwhelmed with spam, disinformation campaigns and disingenuous communications the rallying cry that "free speech" means somebody has to give you a printing press for free just doesn't ring true.
      No, we don't, it's that simple.EDIT: If you have to fight in order to not fight, you have already lost the fight to not fight.<br>Cute, ain't it?The situation is somewhat reflected in the phrase from the Trainspotting:  "I choose not to choose ~whatever~.<br>I choose something else".
      If you want to see some real aggressive behavior, look at HN during its first year.<br>I was shocked.<br>My rose tinted glasses made year one look a lot nicer than it was.
      
      Perhaps everyone is always combative and I'm just sensitive to it lately.
      A lot of it seems to be formerly excited about startups people screwed over by bad management in one way or another who now are happy to hang out at FAANG and focus on money.I get it.<br>My last employer made a lot of their employees want to join large companies and focus on stuffing their pockets rather than caring about any higher goal.
      
      
      
      
      
      
      
      As an aside, I also stop reading after "I think it's funny..." or "Interesting that..." because it's usually something very passive-aggressive
      
      
      Many top comments here often have overt political bias on a range of topics, including the pandemic.<br>I find it irritating, I'm sure others do too.<br>As a result I spend much less (20% ish) the amount of time on HN that I used to say 8-3 years ago.
      
      
      It's more likely that the community never changed, but that  are changing.<br>You may have become more sensitive over time, and now feel that anger more viscerally, and assume that this new feeling must be the community changing rather than yourself.I know I've gotten both softer and harder over time.<br>I can feel my reactions getting stronger, but I also try to shut up when I feel I'm about to react strongly.<br>I've gotten a little better at making my words more diplomatic.<br>But I'm really just as angry as I've always been :-)
      Now, I think we're closer than ever to a real split.<br> Covid has exacerbated it all.<br> People are self-sorting in terms of migrations from blue states to red states, and from cities to suburbs and rural areas.This summer, and the elections in November, could be flashpoints of something larger and worse -- I hope we can hold it together.As for HN toxicity -- beware items whose number of comments exceeds the votes for the article itself; it's a rough metric for how big the flames are.
      I feel like people on Reddit, and to a lesser extent on HN, are trying now, more than ever before, to label and sort themselves into "us" and "them".Commenting on a post didn't used to require as a compulsory first step announcing which "us" you belong to.In a nutshell:us = rational and fact-basedthem = irrational and emotion-basedAll sides think they're "us" and that other sides are "them".
      But what happens when half of everyone wears a mask and the other half does not?
      
      same with the "I remade a frontend for HN" someone always posts one.<br>hell, i even made one a long time ago haha
      The trouble is that tech and the startup community in general derive much of their meaning from the idea that "tomorrow will be better".<br>Nearly all programmers that I know, got into the field because of what they dream it could be tomorrow.<br>There is an implicitly understanding that the things we build today are just the foundation for a brighter future.In a more practical, less ideological sense, the entire startup/VC ecosystem  on tomorrow being better and brighter since everything we are doing is leveraged against the future, literally.<br>If the future were to be  than today, that would ultimately fall apart.However, as the signs that the future is dimming become more apparent, the vast majority of the HN community are forced into a position of existential angst that they are not prepared for.This leads to a general increase in hostility about any topic related to a changing world.<br>People will lose their minds in discussions about remote work (especially people who want to return to "normal", discussion of pandemic is filled with people who don't want to vaccinate or wear masks as a means of denying the pandemic is happening, climate change articles are filled with denial comments almost immediately, and very offend flagged off the home page very quickly.Many members of this community are under extreme stress and anxiety because a reality they don't want to see continues to creep in.<br>The result of this an angrier more agressive, more scared community.
      It's a mild virus that still hasn't even done in 0.3% of my country (by contrast, almost 3% of my lifespan has passed in the time period) and it's rapidly approaching a complete non issue.Comparing it to climate change is dangerous because climate change is actually an existential issue for humanity in a way that just another virus is not.<br>We've had viruses before, we will have them again.
      
      
      I'm guessing people vouched for his post here, despite the fact that it's really continuing to do the same...
      
      
      
      I don't think most people on HN are angry.<br>You're just affected more by angry comments than rational, calm ones.<br>It's an emotional bias.<br>This is why it's important to not use social media for the vast majority of one's time; angry people have a way of creating more angry people around them.
      </p>
