<p>Take a closer look at Iran’s state-sponsored hacking groupsHuman error bugs increasingly making a splash, study indicatesSoftware supply chain attacks – everything you need to knowNorth Korean cyber-threat groups become top-tier adversariesHow expired web domains are helping criminal hacking campaignsThe latest programs for January 2022A schedule of events in 2021 and beyondInadvertent defense downgrade quickly revertedDevelopers of the Symfony PHP framework have reversed a recent change that inadvertently turned off protection against  (CSRF) attacks.Symfony is a popular  framework for web and console applications.<br>The Symfony form component of the open source software features a CSRF protection mechanism that relies on a random token injected in the form.This protection can be enabled or disabled by changing the configuration setup of the framework.<br>Protection was enabled by default until a recent change in how the configuration was loaded meant that CSRF protection was turned off and needed to be explicitly enabled.<br>CSRF vulnerabilities creates a mechanism for attackers to trick users into carrying out actions they did not intend to perform.<br>The problem arises in cases where it’s possible for different websites to interfere with each other.Modern  such as Chrome as well as web development frameworks such as Symfony feature built-in protection against CSRF attacks.Users of affected versions of Symfony (5.3.14 and earlier, 5.4.0-5.4.3, and 6.0.0-6.03) need to upgrade to patched versions, as explained in  posted on GitHub.The issue – tracked as  – notched a CVSS score of 8.1.<br>Because of its high impact early remediation is recommended.<br>
        
        
        
    
            
        Burp SuiteVulnerabilitiesCustomersCompanyInsights© 2022 PortSwigger Ltd.Take a closer look at Iran’s state-sponsored hacking groupsHuman error bugs increasingly making a splash, study indicatesSoftware supply chain attacks – everything you need to knowNorth Korean cyber-threat groups become top-tier adversariesHow expired web domains are helping criminal hacking campaignsThe latest programs for January 2022A schedule of events in 2021 and beyondInadvertent defense downgrade quickly revertedDevelopers of the Symfony PHP framework have reversed a recent change that inadvertently turned off protection against  (CSRF) attacks.Symfony is a popular  framework for web and console applications.<br>The Symfony form component of the open source software features a CSRF protection mechanism that relies on a random token injected in the form.This protection can be enabled or disabled by changing the configuration setup of the framework.<br>Protection was enabled by default until a recent change in how the configuration was loaded meant that CSRF protection was turned off and needed to be explicitly enabled.<br>CSRF vulnerabilities creates a mechanism for attackers to trick users into carrying out actions they did not intend to perform.<br>The problem arises in cases where it’s possible for different websites to interfere with each other.Modern  such as Chrome as well as web development frameworks such as Symfony feature built-in protection against CSRF attacks.Users of affected versions of Symfony (5.3.14 and earlier, 5.4.0-5.4.3, and 6.0.0-6.03) need to upgrade to patched versions, as explained in  posted on GitHub.The issue – tracked as  – notched a CVSS score of 8.1.<br>Because of its high impact early remediation is recommended.<br>
        
        
        
    
            
        Burp SuiteVulnerabilitiesCustomersCompanyInsights© 2022 PortSwigger Ltd.Take a closer look at Iran’s state-sponsored hacking groupsHuman error bugs increasingly making a splash, study indicatesSoftware supply chain attacks – everything you need to knowNorth Korean cyber-threat groups become top-tier adversariesHow expired web domains are helping criminal hacking campaignsThe latest programs for January 2022A schedule of events in 2021 and beyondInadvertent defense downgrade quickly revertedDevelopers of the Symfony PHP framework have reversed a recent change that inadvertently turned off protection against  (CSRF) attacks.Symfony is a popular  framework for web and console applications.<br>The Symfony form component of the open source software features a CSRF protection mechanism that relies on a random token injected in the form.This protection can be enabled or disabled by changing the configuration setup of the framework.<br>Protection was enabled by default until a recent change in how the configuration was loaded meant that CSRF protection was turned off and needed to be explicitly enabled.<br>CSRF vulnerabilities creates a mechanism for attackers to trick users into carrying out actions they did not intend to perform.<br>The problem arises in cases where it’s possible for different websites to interfere with each other.Modern  such as Chrome as well as web development frameworks such as Symfony feature built-in protection against CSRF attacks.Users of affected versions of Symfony (5.3.14 and earlier, 5.4.0-5.4.3, and 6.0.0-6.03) need to upgrade to patched versions, as explained in  posted on GitHub.The issue – tracked as  – notched a CVSS score of 8.1.<br>Because of its high impact early remediation is recommended.<br>
        
        
        
    
            
        Burp SuiteVulnerabilitiesCustomersCompanyInsights© 2022 PortSwigger Ltd.</p>
